{
  imports = [
    #./bash.nix
    ./mpv.nix
    ./mmex.nix
    ./yazi.nix
    ./i3.nix
    ./i3status.nix
    ./lazygit.nix
    ./aspell.nix
    ./anki-service.nix
    ./tmux.nix
    ./kitty.nix
    ./gtk.nix
    ./tmux-sessionizer.nix
    #./mixxx.nix
    ./newsboat.nix
    ./fzf.nix
    ./zsh.nix
    ./starship.nix
    #./i3blocks.nix
    ./nvim
  ];
}
